name: nsopoikha_wiki_tool
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
  html: ^0.15.4
  intl: ^0.19.0
  timezone: ^0.9.2
  markdown: ^7.2.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  nwtool: nwtool_core.dart
